/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconFaceTime: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg width="60px" height="77px" viewBox="0 0 60 77" version="1.1">
      <title>FaceTime</title>
      <desc>Created with Sketch.</desc>
      <defs>
        <linearGradient
          x1="50%"
          y1="0%"
          x2="50%"
          y2="100%"
          id="linearGradient-1"
        >
          <stop stop-color="#67FF81" offset="0%" />
          <stop stop-color="#00B41E" offset="100%" />
        </linearGradient>
      </defs>
      <g
        id="Page-1"
        stroke="none"
        stroke-width="1"
        fill="none"
        fill-rule="evenodd"
      >
        <g id="Home" transform="translate(-202.000000, -380.000000)">
          <g id="FaceTime" transform="translate(202.000000, 380.000000)">
            <text
              id="Messages-"
              font-family="Helvetica"
              font-size="12"
              font-weight="normal"
              fill="#FFFFFF"
            >
              <tspan x="2" y="76">
                FaceTime
              </tspan>
            </text>
            <path
              d="M39.0815,0 C45.105,0 48.116,0 51.3585,1.025 C54.8985,2.3135 57.6865,5.1015 58.975,8.6415 C60,11.8835 60,14.8955 60,20.9185 L60,39.0815 C60,45.105 60,48.116 58.975,51.3585 C57.6865,54.8985 54.8985,57.6865 51.3585,58.9745 C48.116,60 45.105,60 39.0815,60 L20.9185,60 C14.895,60 11.8835,60 8.6415,58.9745 C5.1015,57.6865 2.3135,54.8985 1.025,51.3585 C0,48.116 0,45.105 0,39.0815 L0,20.9185 C0,14.8955 0,11.8835 1.025,8.6415 C2.3135,5.1015 5.1015,2.3135 8.6415,1.025 C11.8835,0 14.895,0 20.9185,0 L39.0815,0 Z"
              id="Background"
              fill="url(#linearGradient-1)"
            />
            <path
              d="M10,22.9465507 L10,25.9465507 C9.44771525,25.9465507 9,25.4988355 9,24.9465507 L9,23.9465507 C9,23.394266 9.44771525,22.9465507 10,22.9465507 Z M11,38.4211893 L11,21.0253614 C11,19.3614126 12.3614126,18 14.0253614,18 L34.8247209,18 C36.4886697,18 37.8500823,19.3614126 37.8500823,21.0253614 L37.8500823,38.4211893 C37.8500823,40.0851381 36.4886697,41.4465507 34.8247209,41.4465507 L14.0253614,41.4465507 C12.3614126,41.4465507 11,40.0851381 11,38.4211893 Z M39.1191033,29.7232754 L39.1191033,26.6661477 L47.5961659,20.9935951 L47.5961659,29.7232754 L47.5961659,38.4529556 L39.1191033,32.780403 L39.1191033,29.7232754 Z M49.1091491,20.9938976 L50.6091491,20.9938976 L50.6091491,29.7235779 L50.6091491,38.4532582 L49.1091491,38.4532582 L49.1091491,29.7235779 L49.1091491,20.9938976 Z"
              id="facetime-icon"
              fill="#FFFFFF"
            />
          </g>
        </g>
      </g>
    </svg>
  );
};

IconFaceTime.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
