/** Icons generated by create-react-icons. Don't edit this file directly. **/
import * as React from "react";
import PropTypes from "prop-types";

interface IconProps extends React.SVGAttributes<SVGElement> {
  size?: number | string;
  color?: string;
}

export const IconCamera: React.FunctionComponent<IconProps> = ({
  color = "currentColor",
  size = 24,
  ...other
}) => {
  return (
    <svg
      viewBox="0 0 60 76"
      version="1.1"
      height={size}
      width={size}
      {...other}
    >
      <title>Camera</title>
      <desc>Created with Sketch.</desc>
      <defs>
        <linearGradient
          x1="50%"
          y1="0%"
          x2="50%"
          y2="100%"
          id="linearGradient-1"
        >
          <stop offset="0%" stopColor="#DBDDDE" />
          <stop offset="100%" stopColor="#898B91" />
        </linearGradient>
        <linearGradient
          x1="50%"
          y1="0%"
          x2="50%"
          y2="100%"
          id="linearGradient-2"
        >
          <stop offset="0%" stopColor="#474747" />
          <stop offset="100%" stopColor="#2B2B2B" />
        </linearGradient>
        <path
          d="M0,9 L42,9 L42,31 L0,31 L0,9 Z M0,31.9975722 C0,33.3795877 1.11996531,34.5 2.50151253,34.5 L39.4984875,34.5 C40.8766015,34.5 42,33.3796249 42,31.9975722 L42,31.5 L3.55271368e-15,31.5 L0,31.9975722 Z M0,8.5 L0,8.00242778 C0,6.62037508 1.12339854,5.5 2.50151253,5.5 L8.53044963,5.5 C9.45720112,5.41801861 10.3218208,5.24163126 10.9205322,4.89025879 C12.8326425,3.7680772 12.9641113,0.5 15.996205,0.5 L21.026083,0.5 L26.0559611,0.5 C29.0880548,0.5 29.2195236,3.7680772 31.1316339,4.89025879 C31.7303453,5.24163126 32.594965,5.41801861 33.5217165,5.5 L39.4984875,5.5 C40.8800347,5.5 42,6.62041235 42,8.00242778 L42,8.5 L0,8.5 L0,8.5 Z M30.25,20 C30.25,14.8913661 26.1086339,10.75 21,10.75 C15.8913661,10.75 11.75,14.8913661 11.75,20 C11.75,25.1086339 15.8913661,29.25 21,29.25 C26.1086339,29.25 30.25,25.1086339 30.25,20 L30.25,20 Z M13.25,20 C13.25,15.7197932 16.7197932,12.25 21,12.25 C25.2802068,12.25 28.75,15.7197932 28.75,20 C28.75,24.2802068 25.2802068,27.75 21,27.75 C16.7197932,27.75 13.25,24.2802068 13.25,20 L13.25,20 Z"
          id="path-3"
        />
        <filter
          x="-1.2%"
          y="-1.5%"
          width="102.4%"
          height="105.9%"
          filterUnits="objectBoundingBox"
          id="filter-4"
        >
          <feOffset
            dx="0"
            dy="1"
            in="SourceAlpha"
            result="shadowOffsetOuter1"
          />
          <feColorMatrix
            values="0 0 0 0 1   0 0 0 0 1   0 0 0 0 1  0 0 0 0.5 0"
            type="matrix"
            in="shadowOffsetOuter1"
          />
        </filter>
        <filter
          x="-3.6%"
          y="-4.4%"
          width="107.1%"
          height="111.8%"
          filterUnits="objectBoundingBox"
          id="filter-5"
        >
          <feGaussianBlur
            stdDeviation="1"
            in="SourceAlpha"
            result="shadowBlurInner1"
          />
          <feOffset
            dx="0"
            dy="1"
            in="shadowBlurInner1"
            result="shadowOffsetInner1"
          />
          <feComposite
            in="shadowOffsetInner1"
            in2="SourceAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
            result="shadowInnerInner1"
          />
          <feColorMatrix
            values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.3 0"
            type="matrix"
            in="shadowInnerInner1"
            result="shadowMatrixInner1"
          />
          <feGaussianBlur
            stdDeviation="0.5"
            in="SourceAlpha"
            result="shadowBlurInner2"
          />
          <feOffset
            dx="0"
            dy="1"
            in="shadowBlurInner2"
            result="shadowOffsetInner2"
          />
          <feComposite
            in="shadowOffsetInner2"
            in2="SourceAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
            result="shadowInnerInner2"
          />
          <feColorMatrix
            values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.3 0"
            type="matrix"
            in="shadowInnerInner2"
            result="shadowMatrixInner2"
          />
          <feGaussianBlur
            stdDeviation="0.5"
            in="SourceAlpha"
            result="shadowBlurInner3"
          />
          <feOffset
            dx="0"
            dy="0"
            in="shadowBlurInner3"
            result="shadowOffsetInner3"
          />
          <feComposite
            in="shadowOffsetInner3"
            in2="SourceAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
            result="shadowInnerInner3"
          />
          <feColorMatrix
            values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.3 0"
            type="matrix"
            in="shadowInnerInner3"
            result="shadowMatrixInner3"
          />
          <feGaussianBlur
            stdDeviation="0.5"
            in="SourceAlpha"
            result="shadowBlurInner4"
          />
          <feOffset
            dx="0"
            dy="0"
            in="shadowBlurInner4"
            result="shadowOffsetInner4"
          />
          <feComposite
            in="shadowOffsetInner4"
            in2="SourceAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
            result="shadowInnerInner4"
          />
          <feColorMatrix
            values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.3 0"
            type="matrix"
            in="shadowInnerInner4"
            result="shadowMatrixInner4"
          />
          <feMerge>
            <feMergeNode in="shadowMatrixInner1" />
            <feMergeNode in="shadowMatrixInner2" />
            <feMergeNode in="shadowMatrixInner3" />
            <feMergeNode in="shadowMatrixInner4" />
          </feMerge>
        </filter>
        <path
          d="M4,4.25 C4,3.83578644 4.33559471,3.5 4.75083781,3.5 L6.74916219,3.5 C7.16383846,3.5 7.5,3.83289862 7.5,4.25 L7.5,5 L4,5 L4,4.25 L4,4.25 Z"
          id="path-6"
        />
        <filter
          x="0.0%"
          y="0.0%"
          width="100.0%"
          height="100.0%"
          filterUnits="objectBoundingBox"
          id="filter-7"
        >
          <feOffset
            dx="0"
            dy="0"
            in="SourceAlpha"
            result="shadowOffsetOuter1"
          />
          <feColorMatrix
            values="0 0 0 0 1   0 0 0 0 1   0 0 0 0 1  0 0 0 0.5 0"
            type="matrix"
            in="shadowOffsetOuter1"
          />
        </filter>
        <filter
          x="-14.3%"
          y="-33.3%"
          width="128.6%"
          height="166.7%"
          filterUnits="objectBoundingBox"
          id="filter-8"
        >
          <feOffset
            dx="0"
            dy="1"
            in="SourceAlpha"
            result="shadowOffsetInner1"
          />
          <feComposite
            in="shadowOffsetInner1"
            in2="SourceAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
            result="shadowInnerInner1"
          />
          <feColorMatrix
            values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0"
            type="matrix"
            in="shadowInnerInner1"
          />
        </filter>
        <circle id="path-9" cx="30.5" cy="12" r="1" />
        <filter
          x="0.0%"
          y="0.0%"
          width="100.0%"
          height="100.0%"
          filterUnits="objectBoundingBox"
          id="filter-10"
        >
          <feOffset
            dx="0"
            dy="0"
            in="SourceAlpha"
            result="shadowOffsetOuter1"
          />
          <feColorMatrix
            values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.5 0"
            type="matrix"
            in="shadowOffsetOuter1"
          />
        </filter>
        <filter
          x="-25.0%"
          y="-25.0%"
          width="150.0%"
          height="150.0%"
          filterUnits="objectBoundingBox"
          id="filter-11"
        >
          <feGaussianBlur
            stdDeviation="0.5"
            in="SourceAlpha"
            result="shadowBlurInner1"
          />
          <feOffset
            dx="0"
            dy="0"
            in="shadowBlurInner1"
            result="shadowOffsetInner1"
          />
          <feComposite
            in="shadowOffsetInner1"
            in2="SourceAlpha"
            operator="arithmetic"
            k2="-1"
            k3="1"
            result="shadowInnerInner1"
          />
          <feColorMatrix
            values="0 0 0 0 0   0 0 0 0 0   0 0 0 0 0  0 0 0 0.3 0"
            type="matrix"
            in="shadowInnerInner1"
          />
        </filter>
      </defs>
      <g
        id="Page-1"
        stroke="none"
        fill="none"
        strokeWidth="1"
        fillRule="evenodd"
      >
        <g id="Home" transform="translate(-289.000000, -28.000000)">
          <g id="Camera" transform="translate(289.000000, 28.000000)">
            <text
              fill={color}
              fontFamily="Helvetica"
              fontSize="12"
              fontWeight="normal"
            >
              <tspan x="8" y="75">
                Camera
              </tspan>
            </text>
            <g id="Camera-icons">
              <g id="Camera-Icon">
                <path
                  d="M39.0815,0 C45.105,0 48.116,0 51.3585,1.025 C54.8985,2.3135 57.6865,5.1015 58.975,8.6415 C60,11.8835 60,14.8955 60,20.9185 L60,39.0815 C60,45.105 60,48.116 58.975,51.3585 C57.6865,54.8985 54.8985,57.6865 51.3585,58.9745 C48.116,60 45.105,60 39.0815,60 L20.9185,60 C14.895,60 11.8835,60 8.6415,58.9745 C5.1015,57.6865 2.3135,54.8985 1.025,51.3585 C0,48.116 0,45.105 0,39.0815 L0,20.9185 C0,14.8955 0,11.8835 1.025,8.6415 C2.3135,5.1015 5.1015,2.3135 8.6415,1.025 C11.8835,0 14.895,0 20.9185,0 L39.0815,0 Z"
                  id="Background"
                  fill={color}
                />
                <g id="Icon" transform="translate(9.000000, 11.000000)">
                  <g id="Camera">
                    <use fill={color} filter="url(#filter-4)" fillOpacity="1" />
                    <use fill={color} fillRule="evenodd" />
                    <use fill={color} filter="url(#filter-5)" fillOpacity="1" />
                  </g>
                  <g id="Path">
                    <use fill={color} filter="url(#filter-7)" fillOpacity="1" />
                    <use fill={color} fillRule="evenodd" />
                    <use fill={color} filter="url(#filter-8)" fillOpacity="1" />
                  </g>
                  <g id="Oval">
                    <use
                      fill={color}
                      filter="url(#filter-10)"
                      fillOpacity="1"
                    />
                    <use fill={color} fillRule="evenodd" />
                    <use
                      fill={color}
                      filter="url(#filter-11)"
                      fillOpacity="1"
                    />
                  </g>
                </g>
              </g>
            </g>
          </g>
        </g>
      </g>
    </svg>
  );
};

IconCamera.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
